version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net

  frontend:
    build: ./frontend  # Asegúrate que esta ruta es correcta
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge