# Usar Node.js 20 para construir la app Angular
FROM node:20-alpine AS build

WORKDIR /app

# Copiar archivos de Angular
COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Construir la aplicación Angular
RUN npm run build --prod

# Usar Nginx para servir la app
FROM nginx:stable-alpine

COPY --from=build /app/dist/ecommerce-frontend /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]